server:
  port: 9009

spring:
  h2:
    console:
      enabled: true
      settings:
        web-allow-others: true
      path: /h2-console
  datasource:
    url: jdbc:h2:tcp://localhost/~/testdb
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create

sms:
  auth_no: 123456
  url: http://127.0.0.1:15001/

login_token:
  expiration_time: 100000
  secret: logintokenabcdefghijklnmopqrstuvwxyzfghijklnmopqrstuvwxyzfghijklnmopqrstuvwxyzfghijklnmopqrstuvwxyz

auth_token:
  expiration_time: 100000
  secret: authtokenabcdefghijklnmopqrstuvwxyzfghijklnmopqrstuvwxyzfghijklnmopqrstuvwxyzfghijklnmopqrstuvwxyz

logging:
  level:
    com.ably.api.userapi: DEBUG